name: Moodle Sync Job



on:
  
  schedule:
    - cron: "0 */4 * * *"  # ทุก 20 นาที
  workflow_dispatch: # กดรันเองได้

jobs:
  run-sync:
    runs-on: ubuntu-latest

    steps:
      - name : Show Trigger
        run : echo "${{ github.event_name }}"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node moodle-google-sheet.js